{% set version = "0.20.dev" %}
{% set name = "scikit-learn" %}
{% set variant = "openblas" %}
{% set commit = "8d7ce8e7b3a2e8bb7aa7ba1b6930c8321de9a183" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/scikit-learn/scikit-learn/archive/{{ commit }}.zip
  sha256: 6f2dd73f1f9cfc3784f2e79a184f72a34bc5716ca4a059bbc3058970c3f862d3
  patches:
    ####################################################################
    # Use GEMV in enet_coordinate_descent                              #
    #                                                                  #
    # xref: https://github.com/scikit-learn/scikit-learn/pull/11507    #
    ####################################################################
    - PR_11507.patch
    ####################################################################
    # Cythonize _update_dict                                           #
    #                                                                  #
    # xref: https://github.com/scikit-learn/scikit-learn/pull/11874    #
    ####################################################################
    - PR_11874.patch
    ####################################################################
    # Some minor performance improvements for enet_coordinate_descent  #
    #                                                                  #
    # xref: https://github.com/scikit-learn/scikit-learn/pull/11898    #
    ####################################################################
    - PR_11898.patch

build:
  number: 202
  # We lack scipy on Windows, and therefore can't build numpy there either currently.
  skip: true  # [win]
  features:
    - blas_{{ variant }}
  script: python -m pip install --no-deps --ignore-installed .  --verbose

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - cython
    - setuptools
    - blas 1.1 {{ variant }}
    - openblas
    - numpy
    - scipy
    - pytest
  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas
    - {{ pin_compatible('numpy') }}
    - scipy

test:
  requires:
    - pytest
  imports:
    - sklearn
  commands:
    - pytest --pyargs sklearn
    - conda inspect linkages -p $PREFIX scikit-learn  # [not win]
    - conda inspect objects -p $PREFIX scikit-learn  # [osx]

about:
  home: http://scikit-learn.org/
  license: BSD 3-Clause
  license_file: COPYING
  summary: A set of python modules for machine learning and data mining

extra:
  recipe-maintainers:
    - amueller
    - astaric
    - jakirkham
    - ogrisel
    - ocefpaf
    - lesteve
